Summary:	Convert Nero's NRG images to ISO9660
Summary(pl.UTF-8):   Konwersja obrazów NRG programu Nero na format ISO9660
Name:		nrg2iso
Version:	0.4
Release:	1
License:	GPL
Group:		Applications/System
Source0:	http://gregory.kokanosky.free.fr/v4/linux/%{name}-%{version}.tar.gz
# Source0-md5:	996c38c8f1465e9c51ccad4f31ec2eee
URL:		http://gregory.kokanosky.free.fr/v4/linux/nrg2iso.en.html
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
Nrg2Iso is a linux utility for converting CD image generated by Nero
Burning Rom to ISO 9660 format.

%description -l pl.UTF-8
Nrg2Iso jest linuksowym narzędziem do konwertowania obrazów płyt CD
generowanych przez program Nero Burning Rom na format ISO 9660.

%prep
%setup -q

%build
%{__cc} %{rpmldflags} -o nrg2iso %{rpmcflags} nrg2iso.c

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT%{_bindir}

install nrg2iso $RPM_BUILD_ROOT%{_bindir}

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc CHANGELOG
%attr(755,root,root) %{_bindir}/*
